CREATE TABLE QUESTIONS(
QUESTION_ID VARCHAR
TUTOR_ID VARCHAR (5) NOT NULL,
CATEGORY VARCHAR (2) NOT NULL,
MODL INT (2) NOT NULL,
SUB_MOD INT (2) NOT NULL,
THEME INT (2) NOT NULL,
DIF INT (1) NOT NULL,
QUESTION VARCHAR (500) NOT NULL,
ANSWER_T VARCHAR (500) NOT NULL,
ANSWER_B VARCHAR (500) NOT NULL,
ANSWER_C VARCHAR (500) NOT NULL
)

CREATE TABLE QUESTIONNAIRES(
ID INT (5) NOT NULL UNIQUE PRIMARY KEY,
QUESTIONNAIRE TEXT NOT NULL,
ANSWERS TEXT NOT NULL
)

CREATE TABLE TUTORS(
TUTOR_ID VARCHAR (5) UNIQUE PRIMARY KEY NOT NULL,
PASSWORD VARCHAR (10) NOT NULL
)