CREATE TABLE QUESTIONS(
TUTOR_ID VARCHAR (5) NOT NULL,
CATEGORY VARCHAR (4) NOT NULL,
MODL INT (2) NOT NULL,
SUB_MOD INT (2) NOT NULL,
THEME INT (2) NOT NULL,
DIF INT (1) NOT NULL,
QUESTION VARCHAR (500) NOT NULL,
ANSWER_T VARCHAR (500) NOT NULL,
ANSWER_B VARCHAR (500) NOT NULL,
ANSWER_C VARCHAR (500) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QUESTIONNAIRES(
ID INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
QUESTIONNAIRE MEDIUMTEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TUTORS(
TUTOR_ID VARCHAR (5) UNIQUE PRIMARY KEY NOT NULL,
PASSWORD VARCHAR (10) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SESSIONS(
SID varchar(50) UNIQUE PRIMARY KEY NOT NULL,
TUTOR_ID VARCHAR(5) NOT NULL,
EXPIRATION_TIME TIMESTAMP NOT NULL
)